INSERT INTO "UTILISATEUR" (IDUTILISATEUR, NOM, PRENOM, MAIL, PASSWORD, ROLE) VALUES(1, 'LAQUAY', 'Jerome', 'mail', '1234', 1);

INSERT INTO "LANGUE" (IDLANGUE, NOMLANGUE) VALUES(1, 'anglais');
INSERT INTO "LANGUE" (IDLANGUE, NOMLANGUE) VALUES(2, 'francais');

INSERT INTO "DOMAINE" (IDDOMAINE, NOM, DESCRIPTION) VALUES(1, 'informatique', 'tout sur l info');
INSERT INTO "DOMAINE" (IDDOMAINE, NOM, DESCRIPTION) VALUES(2, 'commerce', 'tout sur le commerce');


INSERT INTO "ARTICLE" (IDARTICLE, TITRE, CONTENU, DATEPUBLICATION, SOURCE, UTILISATEUR_IDUTILISATEUR, DOMAINE_IDDOMAINE, LANGUE_IDLANGUE) VALUES(1, 'TITRE1', 'CONTENU1', '13/03/1993', 'SOUCRE1', 1 , 1 , 1);

INSERT INTO "ANALYSE" (IDANALYSE, ARGUMENTATION, VOCABULAIRE_SCORE, TRADUCTION_SCORE, GRAMMAIRE_SCORE, IDEE_GLOBAL_SCORE, ANALYSE_SCORE, UTILISATEUR_IDUTILISATEUR, ARTICLE_IDARTICLE, LANGUE_IDLANGUE) VALUES(1, 'ARG', 1, 2, 3, 4, 5, 1, 1, 1);

